### ISSUE TITLE
Rewrite Android Integration Tests using Calabash

### ISSUE THREAD

**Issue by tomclement** [rapidftr/tracker#100]
We recently switched our Android Integration Test Framework from Robotium to Calabash. A by-product of this is that we now need to rewrite the existing Robotium tests using Calabash.

The Integration tests were previously organised by Activity. Presently, there seems to be no need to alter this organisation. 

The integration tests for the Login Activity and Register Child Activity have already been completed. We now need to write the integration tests for:
- [x] Searching for Children
- [ ] Creating Enquiries
- [x] Data Syncing
- [x] Unverified Users
- [x] Viewing all Children
- [ ] Viewing all Enquiries
- [x] General Navigation

**Comment by JamesMura** [comment]
Hey @tomclement how do I get started on moving migrating one of these scenarios ? making sure no one else is working on the same , are there separate issues for each ?

**Comment by tomclement** [comment]
Hey @JamesMura, thanks for expressing interest in this. If you'd like to pick any of the above, you can simply comment here to indicate which part of you've picked up, and I'll update the issue to indicate that you're working on a particular activity.

**Comment by tomclement** [comment]
Splitting this card for more grained tracking and to better provide context. The new cards are:
- #157 - Syncing
- #158 - Enquiries
- #159 - Child Records
- #160 - Search

**Comment by tomclement** [comment]
Hey @JamesMura this card has been split up and each of the automation stories can now be picked up independently. Closing this as this is no longer required.
