### ISSUE TITLE
Remove ContactInformation, use User model instead

### ISSUE THREAD

**Issue by rdsubhas** [rapidftr/tracker#101]
There is a separate model, controller, database and views for a `ContactInformation` model, which is unnecessary. It is the same as the `User` model, with same fields like location, address, phone, email, etc. So just add a flag to `User`, saying whether he/she can share contact details or not, and then make the `Contact Information` link show all the users' information whose contact info is shared. This results in a much simpler code and can do away with one unnecessary MVC.

**Comment by tomclement** [comment]
Resolved with https://github.com/rapidftr/RapidFTR/pull/738 - thanks to @alxndrsn
