### ISSUE TITLE
Update RapidFTR-1.2.1 APK after Better Error Messages is QAd

### ISSUE THREAD

**Issue by rdsubhas** [rapidftr/tracker#105]
Update the APK in http://bit.ly/rapidftr after QA okays #30 

Edit: Changed link

**Comment by duelinmarkers** [comment]
That link does not work as intended. (Sends me to some patten dot edu page.)

Also, will there be tasks like this after QA of every user-facing Android story? Can we instead use the original issue to track getting the change to deployment rather than introducing a separate issue?

**Comment by baziwane** [comment]
Hi @duelinmarkers, the correct link is http://bit.ly/rapidftr

**Comment by rdsubhas** [comment]
Hi @duelinmarkers Nope there won't be a task like this after every story. This was more for the End Release artifact for version 1.2.1 (one-off task).

Snapshot APKs are automatically deployed after every commit, through [Snap-CI](https://snap-ci.com/rapidftr/RapidFTR---Android/)

**Comment by tomclement** [comment]
Looks good!
