### ISSUE TITLE
Images getting corrupted on migrating

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#106]
Tracking open issues from #26 as a result of upgrading to Rails 4, Ruby 2.0 and CouchDB 
- [x] No error messages in logs (rescue_from is gobbling errors)
- [x] Images are getting corrupted when migrating

**Comment by rdsubhas** [comment]
Fixed Image corruption in master, Need to backport that to 1.2.1

**Comment by rdsubhas** [comment]
Ok confirmed, no need to backport the image problem - it works fine in 1.2.1, so the base64 decoding is a result of CouchREST :exclamation:

**Comment by rdsubhas** [comment]
All done, need to move demo.rapidftr.com to some other server and actually migrate the images.

**Comment by ctumwebaze** [comment]
@subhas, what is CouchREST doing that is messing up our images?

**Comment by rdsubhas** [comment]
@ctumwebaze not clear yet, but its messing up with raw/base64 encodings.
