### ISSUE TITLE
Change Android Integration tests to Calabash or Expresso

### ISSUE THREAD

**Issue by rdsubhas** [rapidftr/tracker#11]
Presently the integration tests that we're using on Android use Robotium, which is good but getting very difficult to create and maintain. We want to switch to one of these libraries:
- [Calabash](http://calaba.sh/) - Cucumber like integration tests for Android
- [Expresso](https://code.google.com/p/android-test-kit/w/list) - Google's android testing tools

We're presently preferring Calabash, but we also want the integration tests to be more performant, since it takes a long time to run in the emulator.

We also want to get rid of the Multi-module maven project because of the integration test suite, and switch it to a single-module maven project. This will make IDE integration even simpler.

**Comment by rdsubhas** [comment]
This has been picked up by @tomclement and Robert. They're working on Calabash right now.

**Comment by tomclement** [comment]
The choice was made to go with Calabash, and Robotium has already been swapped out. Instructions for running tests with the new framework can be found on the [Running Tests](https://github.com/rapidftr/RapidFTR---Android/wiki/Running-Tests) section of the wiki
