### ISSUE TITLE
Search for enquiries and view the search results

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#114]
The ability to search for information is a standard requirement in many systems. Currently RapidFTR supports both basic and advanced searching for child registration information. This feature is an enhancement of the existing search in order to support searching for enquiries. A typical user with permissions will provide a term in a search field and view list of enquiries that match the search term.

**Comment by baziwane** [comment]
Hi @scampo for this feature our thoughts are:

Option 1: To move the global search field to the view children and view enquiries pages respectively in order to make it more contextual with the records the user is viewing as shown in screenshot below). 

Option 2: We leave it at the top/global level but in order to support searching for enquiries we'd have to add a toggle (e.g. radio button) for user to select which form set (enquiries vs children) to search. 

Lastly, pls confirm:
1) No blank searches - a user has to provide some text to search. 
2) Support for wild card e.g. entering \* returns all records in system? or just your own records?
![screen shot 2014-09-02 at 10 16 19 am](https://cloud.githubusercontent.com/assets/4676831/4115147/7d7c8f54-3273-11e4-8b60-d8a62d1fc36b.png)

**Comment by baziwane** [comment]
AC Scenarios
AC2: Field worker submitting a keyword and views matching results
AC3: Support for accented characters

**Comment by baziwane** [comment]
Duplicated in  #64

**Comment by tomclement** [comment]
Adding notes from duplicate card https://github.com/rapidftr/tracker/issues/64:
- This is for the web
- We will have a dropdown that lets the user choose to search through children or through enquiries
- The dropdown will default to Children
- This card does not involve Advanced Search

**Comment by tomclement** [comment]
Feature added with https://github.com/rapidftr/RapidFTR/pull/734. Looks good
