### ISSUE TITLE
using private method proxy_for in RSpec::Mocks

### ISSUE THREAD

**Issue by BriocheBerlin** [rapidftr/tracker#117]
In https://github.com/rspec/rspec-mocks/commit/e6858679feb9755e0ef6a3eb9c6c6c5e2ef8e087 Myron Marston says that this method should only be used internally.

**Comment by rdsubhas** [comment]
Hi @BriocheBerlin I'm closing this, But since this is only a Task of #78 Rspec 3 upgrade - please add these as comments to that story rather than raising new issues.
