### ISSUE TITLE
Spike Docker for Deployment

### ISSUE THREAD

**Issue by rdsubhas** [rapidftr/tracker#118]
Spike using Docker for Deployment - Refer google group discussion:

https://groups.google.com/d/msg/rapidftr/gbIw6xfMDXk/HvaDSzHs_N4J

**Comment by rdsubhas** [comment]
```
docker build -t "rapidftr-image" .
docker run --rm -p 5984:5984 -p 80:80 --name=rapidftr -t rapidftr-image /sbin/my_init --enable-insecure-key
```
- Configured in Production mode, there should be a way to switch Dev & Production
- Database credentials created **before** running

**Comment by baziwane** [comment]
@mwangiann signed up for this.

**Comment by mwangiann** [comment]
docker run -e RAILS_ENV=development --rm -p 5984:5984 -p 80:80 --name=rapidftr -t rapidftr-image /sbin/my_init --enable-insecure-key
- With this command it runs in development mode ensuring that switching is possible between production and development.
