### ISSUE TITLE
Fix deprecation warning from rspec in factories.rb

### ISSUE THREAD

**Issue by kat-crumbs** [rapidftr/tracker#119]
Using `stub` from rspec-mocks' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` instead. Called from /Users/KathiZwick/Code/RapidFTR/spec/factories.rb:23:in `block (3 levels) in <top (required)>'.

**Comment by rdsubhas** [comment]
Hi @kat-crumbs I'm closing this, But since this is only a Task of #78 Rspec 3 upgrade - please add these as comments to that story rather than raising new issues.
