### ISSUE TITLE
Replace tabs with two spaces in ruby files

### ISSUE THREAD

**Issue by kat-crumbs** [rapidftr/tracker#120]

**Comment by rdsubhas** [comment]
Closing this as it has been merged

**Comment by sferik** [comment]
This is not actually fixed. @RapidRailsGirls only added RuboCop in https://github.com/rapidftr/RapidFTR/pull/655. Actually removing the tabs was split off from that pull request. Perhaps it can be reapplied now that https://github.com/rapidftr/RapidFTR/pull/656 has been merged.

**Comment by rdsubhas** [comment]
@sferik oops I thought I was closing the pull request, accidentally closed the issue instead, re-opening this...
