### ISSUE TITLE
Search Results on Mobile have Duplicate Entries

### ISSUE THREAD

**Issue by tomclement** [rapidftr/tracker#134]
**Description**
When a record has more than one highlighted field whose value matches the search parameters, that record appears more than once in the search results. 

For instance, if **name** and **sex** are highlighted fields, and they both have values containing a search query **male** (for instance, **Name: Maley, Sex: Male**), then that particular record will appear in the search results more than once. See below.

![ftrscreen](https://cloud.githubusercontent.com/assets/5906754/3609837/ae1b272c-0d81-11e4-97fa-a2a42d55c1f0.png)

**Expected Result**
All search result entries should be unique

**Comment by andreweskeclarke** [comment]
Fixed when addressing rapidftr/tracker#131
