### ISSUE TITLE
Ability to delete Form Sections

### ISSUE THREAD

**Issue by tomclement** [rapidftr/tracker#136]
Presently when a RapidFTR admin adds a new form section to the forms on the web, it is not possible to delete that form section afterwards. Given that RapidFTR should be as flexible as possible - especially with regard to the forms, it should be possible to delete newly created form sections.

**Comment by baziwane** [comment]
GIVEN that I am an ADMIN
WHEN I am viewing a form section's details
THEN I should see an icon that allows me to delete the form section

GIVEN that I am an ADMIN
WHEN I click on the icon to delete the form section
THEN I should be prompted to confirm whether I wish to delete the section

GIVEN that I am an ADMIN
WHEN I confirm that I wish to delete the form section
THEN the section should no longer appear in the list of form sections
AND I should be able to view a success message "Form section XYZ deleted successfully".

![screen shot 2014-07-29 at 2 53 11 pm](https://cloud.githubusercontent.com/assets/4676831/3734530/366a8d08-1718-11e4-9904-a08b52421681.png)

**Comment by rdsubhas** [comment]
Removing from Kampala Code Jam because this has dependencies on Form Builder for Enquiries #55

**Comment by rdsubhas** [comment]
@baziwane @tomclement this is implemented (thanks to @raoufaghrout and @robmiles), can you pls have a look...

**Comment by baziwane** [comment]
Awesome. Thanks @raoufaghrout and @robmiles

**Comment by robmiles** [comment]
@baziwane check out the discussion in the pull request https://github.com/rapidftr/RapidFTR/pull/693#issuecomment-52078668
We had some trouble with the placing of the Delete button due to nesting of HTML forms so it's not where it was requested in this issue. I also had a question about whether we should be checking the Editable flag of the FormSection?

**Comment by tomclement** [comment]
Taking a look at this...

**Comment by tomclement** [comment]
@raoufaghrout @robmiles The functionality all looks good. Thanks for this! 👍 

However in the meantime we'll be holding this card in [QA Blocked](https://github.com/rapidftr/tracker/labels/Status:%206.%20QA%20Blocked) until this [Pull Request](https://github.com/rapidftr/RapidFTR/pull/695) is reopened and merged. That should ensure we don't forget to fix those tests

**Comment by robmiles** [comment]
No worries - we should have that recommitted fairly soon

**Comment by raouf-aghrout** [comment]
I've just submitted a new pull request that's just running on Travis CI now, fingers crossed!

**Comment by tomclement** [comment]
@RaoufAghrout @robmiles Build passed! Merging this right away..

**Comment by tomclement** [comment]
Functional tests fixed with https://github.com/rapidftr/RapidFTR/pull/700. This is now ready for accepance
