### ISSUE TITLE
While editing the RapidFTR forms, notifications should be displayed whenever changes to the forms are saved

### ISSUE THREAD

**Issue by tomclement** [rapidftr/tracker#139]
While editing form fields or form sections in the RapidFTR Web, there is no feedback provided as to whether an operation has been completed successfully or not. Consequently in cases where there are errors or delays (such as due to slow connectivity), a user may be surprised to learn that the changes they made were actually not effected. 

For example in the screenshot below, the operation to change the order of certain form fields fails but there is no feedback to the user until they reload the page - at which point they would notice that their changes were not saved.

![screen shot 2014-07-21 at 12 54 18 pm](https://cloud.githubusercontent.com/assets/5906754/3642071/0330014a-10bd-11e4-9f45-1f48f6526e10.png)

**Comment by sferik** [comment]
@rdsubhas Maybe a good one for @RapidRailsGirls?

**Comment by rdsubhas** [comment]
@sferik yep you're tracking these issues better than I do ;)

**Comment by kat-crumbs** [comment]
Hi @tomclement an @rdsubhas, yes we'd like to work on this one. 
Just to make sure, we assume this is just for the admin account? Further we assume that is this only about notifications for save_order and toggle, right?

We would start with the notifications in the form_section#index.

**Comment by rdsubhas** [comment]
Hi @kat-crumbs yep this is for the Admin account, and only for the Ajax requests (save_order and toggle).

But just one thing to note - we don't check usernames/accounts directly in the code. We instead check for permissions. I'm writing a Wiki page on that right now...

**Comment by kat-crumbs** [comment]
Hi @tomclement we're about to actually write some code for this issue. But we were wondering what actually should happen, in case there is an error. 
We brainstormed some ideas:
- an alert appears, telling the user something went wrong
- a red message at the top of the page appears
- the form section row turns red and a red message at the top of the page appears

These are just some examples. What did you have in mind?

**Comment by tomclement** [comment]
@kat-crumbs Thanks for picking this up. The idea we had was to just display a non-obtrusive notification indicating whether the save was successful or not. To that extent, the second option you propose - a red message that appears at the top (and does not require user intervention to eventually go away) is sufficient.

**Comment by tomclement** [comment]
Great job @RapidRailsGirls @BriocheBerlin & @kat-crumbs - This is now done!!
