### ISSUE TITLE
Vagrant for Android

### ISSUE THREAD

**Issue by rdsubhas** [rapidftr/tracker#14]
The process of setting up Android in user's machine is very long and complicated. You have to install the SDK, various APIs and Machine Images, create AVDs, etc. For a newcomer having a few hours - it takes the whole time to setup the machine, instead of developing valuable code.

We already have Vagrant for the Rails repository, but we want the same for Android as well, with Chef scripts that will automate the task of installing android and other various stuff. Please check the [Vagrantfile](https://github.com/rapidftr/RapidFTR/blob/master/Vagrantfile) and the relevant [Chef cookbooks](https://github.com/rapidftr/rapidftr-infrastructure) for an idea.

Challenges:
- Android emulator is already slow. Running it inside the VM is going to be even slower! If the base image is Ubuntu, then we must have KVM acceleration enabled. Refer the [Android emulator hardware acceleration](http://developer.android.com/tools/devices/emulator.html#acceleration) page for more details.
- The emulator will run using Xvfb/Xvnc. If SSH X11 forwarding is supported by Vagrant, then we need to use it. Otherwise we can install Xvfb/Xvnc and then forward the VNC port.

**Comment by rdsubhas** [comment]
Looks like KVM acceleration inside VirtualBox virtual machines is not yet supported. There is a [bug open](https://www.virtualbox.org/ticket/4032), try a +1 on it. So the emulator will be very slow when run inside the vagrant guest. Need some other ways to tackle that...

**Comment by rdsubhas** [comment]
Closing this issue as is not yet supported in VirtualBox.

**Comment by kishoreyekkanti** [comment]
We can try using http://www.genymotion.com/ emulator. Its extremely faster when compared to the default android emulator

**Comment by rdsubhas** [comment]
Hey @kishoreyekkanti welcome back :) Genymotion also uses VirtualBox to launch the emulators, so I guess that also falls into the same problem...

Which is - We can use Vagrant to start a VM, but we need to run the emulator (either android or genymotion) _inside_ the VM itself, which means in the case of Genymotion virtualbox inside virtualbox, and that's not yet supported... Any ideas or am I misled?
