### ISSUE TITLE
Change two pages to use Slim template instead of ERB

### ISSUE THREAD

**Issue by rdsubhas** [rapidftr/tracker#146]
Continuation of #13 , refer to that story for more details

Change the following pages to use Slim:
- app/views/admin/index
- app/views/devices/index

**Comment by Teejay005** [comment]
This story has been signed up by Tunji

**Comment by tomclement** [comment]
@Teejay005 @surpass1 [Your pull request](https://github.com/rapidftr/RapidFTR/pull/679) failed on [Travis](https://travis-ci.org/rapidftr/RapidFTR/builds/31157472) - Could you please have a look?

**Comment by tomclement** [comment]
@Teejay005 @surpass1 - No worries. I fixed this (it was just an indentation issue as @rdsubhas rightfully pointed out) and merged it as part of https://github.com/rapidftr/RapidFTR/pull/720. Many thanks for your contributions :-)
