### ISSUE TITLE
Export is broken - Unable to find records to export

### ISSUE THREAD

**Issue by tomclement** [rapidftr/tracker#148]
Export is unable to find records

**Steps to Reproduce:**
- Click the export button on the view children page (making sure you are presently able to see at least one child record in that view)
- Select any option e.g Export All to PDF
- In the dialog that opens, enter any valid password
- Click OK

**Expected Results**
- An export of the records being viewed on the child records page should be generated and downloaded by the browser

**Actual Results**
- The error message `No Records Available!` is displayed

**Comment by baziwane** [comment]
Hide the export to CPIMS button

**Comment by tomclement** [comment]
**[Update]** 
- Clicking the `Export` button on the `Children` page and selecting any of the options _(Export All to CPIMS/PDF/CSV/Photo Wall)_ and entering a password always produces the error `No Records Available!`
- On the _Child search results page_: 
  - Selecting child records and clicking `Export Selected to CPIMS` crashes the application. 
  - Selecting `Export Selected to PDF` produces a PDF with all the selected child records as well as the enquiry form sections
  - Selecting `Export Selected to CSV` or `Export Selected to Photo Wall` works as expected.

Tasks:
- [x] Hide option to _Export to CPIMS_ on both the _Children page_ as well as the _Child search results page_
- [x] Ensure that the PDF produced on clicking `Export Selected to PDF` on the _Child search results page_ does not include any details of the Enquires (form sections and fields - as is currently the case)
- [x] Ensure that selecting _Export All to PDF/CSV/Photo Wall_ performs an actual export of ALL the existing child records, as opposed to displaying the message `No Records Available!`

**Comment by andreweskeclarke** [comment]
Images that have been sync'd from other servers can not be exported to PDF.
