### ISSUE TITLE
Add/Remove highlighted fields for enquiries

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#149]
Highlighted fields display a summary of an enquiry. This feature shall enable an admin to define what fields should appear when viewing a single enquiry on both mobile and web.

**Comment by baziwane** [comment]
GIVEN that I am an ADMIN
AND I am logged into RapidFTR on my server/netbook
WHEN I am viewing highlighted fields in the system settings
THEN I should be able to view an option for highlighted fields for enquiries

GIVEN that I am an ADMIN
WHEN I click on the option for enquiries highlighted fields
THEN I should be able to view the existing highlighted fields for enquiries with a remove icon next to each field
AND I should be able to view an add icon at the bottom of the list

GIVEN that I am an ADMIN
WHEN I click on the add icon at the bottom of the list
THEN I should be able to view a form with all enquiries form sections and respective fields
AND I should be able to select any of the fields in the form to add to existing highlighted fields

GIVEN that I am an ADMIN
WHEN I select a field from the list of enquiries fields
THEN it should be included in the list of highlighted fields at the top of the page with a remove icon next to it.

GIVEN that I am an ADMIN
WHEN I click on the remove icon next to the field name in the list
THEN the field should be removed from the list of highlighted fields

**Comment by baziwane** [comment]
The user journey for this feature will be similar to setting highlighted fields for child registration. Attached is a copy of the child registration screen.
![screen shot 2014-08-01 at 9 59 12 am](https://cloud.githubusercontent.com/assets/4676831/3775756/f4e05014-1949-11e4-8818-37da83f31715.png)

**Comment by tomclement** [comment]
The highlighted fields are either not being propagated to the mobile or the mobile is not using them to display the Enquiries' summary information under `View All`. See rapidftr/tracker/issues/172

**Comment by ctumwebaze** [comment]
​@tomclement, that part of the enquiries story was to be played once the web
counterpart was played. So we should be good to go with implementing
viewing of the highlighted fields.​

On Wed, Aug 13, 2014 at 7:42 PM, Tom Clement Oketch <
notifications@github.com> wrote:

> The highlighted fields are either not being propagated to the mobile or
> the mobile is not using them to display the Enquiries' summary information
> under View All. See rapidftr/tracker#172
> https://github.com/rapidftr/tracker/issues/172
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rapidftr/tracker/issues/149#issuecomment-52075177.

## 

Regards,
_Charles Tumwebaze_ | Consultant
P.O.Box 35294 Kampala Uganda | Email: ctumwebaze@gmail.com
Mob: +256 773 356153, +256 712 513893 | Skype Id: ctumwebaze

**Comment by tomclement** [comment]
Moving this to [Ready for Acceptance](https://github.com/rapidftr/tracker/labels/Status:%208.%20Ready%20for%20Acceptance) since the use of the highlighted fields on the android is now being tracked in #173
