### ISSUE TITLE
Child registration field names and form sections not displaying in 1.2.1 APK

### ISSUE THREAD

**Issue by tomclement** [rapidftr/tracker#155]
In the 1.2.1 APK, performing a sync with the development version of RapidFTR web (2.0) results in the child registration field names and form sections not displaying. See screenshots below:

![screen1](https://cloud.githubusercontent.com/assets/5906754/3794429/eeacb966-1bac-11e4-884b-645002cf9507.png)
![screen2](https://cloud.githubusercontent.com/assets/5906754/3794430/eeb0aab2-1bac-11e4-89ad-0ed554032a83.png)

This breaks the requirement for ensuring backwards compatibility with the 1.2.1 APK in story #53

**Comment by ctumwebaze** [comment]
This was fixed with the recent fix for #53

**Comment by tomclement** [comment]
Resolved with rapidftr/RapidFTR---Android/pull/154
