### ISSUE TITLE
Ensure sure old data gets migrated to new Form Builder

### ISSUE THREAD

**Issue by rdsubhas** [rapidftr/tracker#167]
New Form Builder has `Form > Form Section > Field`.

Old Form Builder has only `Form Section > Field`.

Make sure to write migrations for the old data.

Pinging @baziwane to take a look at this story as well. If there is any "Ensure Backwards Compatibility" story, this can also be added as a sub-task of that.

**Comment by baziwane** [comment]
Closing and transferring context to #153
