### ISSUE TITLE
Missing Template for /users/contact

### ISSUE THREAD

**Issue by tomclement** [rapidftr/tracker#169]
Navigating to `/users/contact` page throws missing template error (see below):

![screen shot 2014-08-13 at 10 45 05 am](https://cloud.githubusercontent.com/assets/5906754/3902434/ca4b8422-22bd-11e4-97ae-63fdde244e30.png)

**Comment by alxndrsn** [comment]
Caused by #101 - check there for desired behaviour.

**Comment by tomclement** [comment]
Resolved with https://github.com/rapidftr/RapidFTR/pull/738 - thanks to @alxndrsn
