### ISSUE TITLE
Use Highlighted Fields on the Android Enquiry list view

### ISSUE THREAD

**Issue by andreweskeclarke** [rapidftr/tracker#173]
The android app should be using the highlighted fields sent from the Ruby app to organize it's list view.  Currently, it only uses the id.

After this card is played:
GIVEN an admin marks an enquiry field as highlighted
AND there are some enquiries for the android user
WHEN the android user syncs
THEN the enquiries "View All" page uses the new highlighted field for each enquiry row

**Comment by baziwane** [comment]
There is more context on this provided in #172
