### ISSUE TITLE
Add/view enquiry photos and audio

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#174]
Split this card from issue #151 to add support for photos and audio for enquiries

**Comment by ctumwebaze** [comment]
Ensure that histories are tracked and displayed for the photo and audio.

**Comment by baziwane** [comment]
GIVEN that I AM a FIELD WORKER
WHEN I am viewing details of an enquiry
THEN I should be able to view any photos attached to the enquiry

GIVEN that I am a FIELD WORKER
WHEN I am creating an enquiry in my web browser
THEN I should be able to attach a photo or audio file to it

~~GIVEN that I am a FIELD WORKER~~
~~WHEN I am creating an enquiry using my mobile device~~
~~THEN I should be able to attach any photos and audio~~

~~GIVEN that I am a FIELD WORKER~~
~~WHEN I attach photos or audio to an enquiry and save using my mobile device~~
~~THEN I should be able to sync the record successfully~~

**Comment by tomclement** [comment]
Moved part of the Acceptance Criteria specified in https://github.com/rapidftr/tracker/issues/174#issuecomment-55853482 to the relevant story in https://github.com/rapidftr/tracker/issues/212

**Comment by tomclement** [comment]
Blocked due to https://github.com/rapidftr/tracker/issues/226
