### ISSUE TITLE
Record a change log for enquiries on mobile

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#175]
This feature will enable recording any activity/change that happens to an enquiry on the mobile device. When a field worker creates or edits an enquiry, a change log should be registered.

**Comment by baziwane** [comment]
GIVEN that I AM A FIELD WORKER
AND I am using my mobile device
WHEN I perform any of the following actions on an enquiry:
- On create
- On update

THEN I should be able to view a change log entry detailing the action performed.

GIVEN that I AM a FIELD WORKER
WHEN I sync my records to the server
THEN I should be able to see these change logs listed on my records

GIVEN that I AM a  SYSTEM ADMINISTRATOR
WHEN I am reading RapidFTR documentation
THEN I want to be able to understand the process of logging changes on mobile devices

**Comment by baziwane** [comment]
Change logs are used for two major purposes: during audit and in case of loss of information on a child. Key considerations:
- Device shouldn't store logs (since they're never displayed on the device)
- Server shouldn't push change logs to the device
- Log each time a record changes (only sync changed records)

**Comment by baziwane** [comment]
Cross-posting an email thread discussion on this issue:
![image](https://cloud.githubusercontent.com/assets/4676831/4384431/83326ba4-43b6-11e4-8680-1620c1303896.png)

**Comment by tomclement** [comment]
Feature added with https://github.com/rapidftr/RapidFTR-Android/pull/181. Approach taken is option 2 (sync everything one child at a time)
