### ISSUE TITLE
Syncing enquiries with dev.rapidftr.com failing

### ISSUE THREAD

**Issue by tomclement** [rapidftr/tracker#178]
Syncing enquiries with dev.rapidftr.com is failing with the error message `The server encountered an error while processing this request. Please contact the system administrator`

**Comment by ctumwebaze** [comment]
We just deleted all the enquiries on dev.rapidftr.com

**Comment by tomclement** [comment]
Syncing enquiries on dev.rapidftr.com was failing because a new system field `updated_at` had been added to enquiries and was therefore expected by the mobile. Newly created enquiries already had this field but the pre-existing enquiries did not - which is why clearing the old data from dev.rapidftr.com was the solution to the problem
