### ISSUE TITLE
Mark/unmark enquiry field as searchable and view resulting matches

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#187]
Create a page that allows an admin to define which fields of an enquiry form to use in searching for matching child records.

**Comment by baziwane** [comment]
GIVEN that I am an ADMIN
WHEN viewing the list of form fields in a form section
THEN I should be able to mark and unmark a field as searchable

GIVEN that I am an ADMIN
WHEN I mark an enquiry field as searchable
THEN I should view all resulting child records matching this field

GIVEN that I am an ADMIN
WHEN I unmark a field as no longer searchable
THEN I shouldn't view child records matched to this field

**Comment by baziwane** [comment]
Hi @scampo just need some context on a scenario related to this card. 
If a user creates an enquiry but doesn't complete any of the searchable/matchable fields (e.g. doesn't complete the child sought form section), do we proceed and save the enquiry knowing it's not "useful"? 
My thought was inclined to saving the enquiry but display a warning at the top that user hasn't filled any searchable fields?? I'm assuming this scenario would only occur in cases when user's intent was to return and complete the enquiry.

**Comment by baziwane** [comment]
@scampo as agreed the scenario is very highly unlikely so we proceed with assumption that this won't happen and thus no need to display warning message as had earlier suggested.

**Comment by tomclement** [comment]
Just noticed that when a field in an enquiry that is matchable is populated with only whitespace, then all existing children are presented as potential matches. I suppose this is a fairly unlikely scenario, but should it happen, it would be very confusing to the user.

Tracking this in rapidftr/tracker/issues/194

**Comment by scampo** [comment]
This is not necessarily unlikely, as incompleteness of fields remains an
issue.

This seems like a bug rather than an acceptable component of the
functionality. This should be resolved.

_____________________
Stuart Campo
Innovation Unit, UNICEF
scampo@unicef.org

+254.718.764526 (Kenya)*
+211.921.379121 (South Sudan)
+256.779.234347 (Uganda)
+1.802.249.8233 (U.S.)
 Skype: stuart.campo

*_currently in Kenya_

www.unicefstories.org

**Comment by tomclement** [comment]
I agree @scampo.. this should be resolved. However, what I mean about it being unlikely is that we are already safeguarding against fields with absolutely no values (as evidenced in this [pull request](https://github.com/rapidftr/RapidFTR/pull/725)). However where the problem arises is if a user unknowingly enters only whitespace into a field - this is where this particular bug would manifest.

**Comment by scampo** [comment]
OK -- that makes sense. Regardless, let's please flag it and address it.

_____________________
Stuart Campo
Innovation Unit, UNICEF
scampo@unicef.org

+254.718.764526 (Kenya)*
+211.921.379121 (South Sudan)
+256.779.234347 (Uganda)
+1.802.249.8233 (U.S.)
 Skype: stuart.campo

*_currently in Kenya_

www.unicefstories.org

On Thu, Sep 4, 2014 at 2:09 PM, Tom Clement Oketch <notifications@github.com

**Comment by tomclement** [comment]
Sure @scampo. We will be holding this story in [QA blocked](https://github.com/rapidftr/tracker/labels/Status:%206.%20QA%20Blocked) until [that bug](https://github.com/rapidftr/tracker/issues/194) is resolved.
