### ISSUE TITLE
Seed searchable enquiry fields

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#189]
Hi @scampo, pls provide the list of fields in enquiries form set that should be seeded in search for matches

**Comment by scampo** [comment]
@baziwane can you please add the scans I sent through here for reference,
Raymond?

_____________________
Stuart Campo
Innovation Unit, UNICEF
scampo@unicef.org

+254.718.764526 (Kenya)*
+211.921.379121 (South Sudan)
+256.779.234347 (Uganda)
+1.802.249.8233 (U.S.)
 Skype: stuart.campo

*_currently in Kenya_

www.unicefstories.org

**Comment by baziwane** [comment]
Hi @scampo, yes here attached. Thx
![scan 4](https://cloud.githubusercontent.com/assets/4676831/4182050/615a9894-3727-11e4-9c01-d8b8f1f8eeac.jpeg)
![scan 5](https://cloud.githubusercontent.com/assets/4676831/4182054/61680c5e-3727-11e4-989f-eae52ec5d833.jpeg)
![scan 6](https://cloud.githubusercontent.com/assets/4676831/4182053/61666eda-3727-11e4-8bdd-88cc20e2047a.jpeg)
![scan 7](https://cloud.githubusercontent.com/assets/4676831/4182051/61608984-3727-11e4-96d4-7386989ff8ae.jpeg)
![scan 8](https://cloud.githubusercontent.com/assets/4676831/4182052/61624846-3727-11e4-90ed-8a526fd5726c.jpeg)

**Comment by tomclement** [comment]
Resolved with https://github.com/rapidftr/RapidFTR/pull/746
