### ISSUE TITLE
Stale potential matches are not removed when enquiry is updated

### ISSUE THREAD

**Issue by tomclement** [rapidftr/tracker#199]
When an enquiry that has potential matches is updated in such a way that any of the potential matches becomes stale (is no longer a potential match), those stale potential matches are not removed from the list of the potential matches.

**Steps to Reproduce**
- Create an enquiry that will cause an existing child record to match. Verify that the child record is listed among the potential matches
- Update the enquiry to exclude the matched child record (such as by clearing all matchable fields)
- Check the list of potential matches

**Expected Result**
The said child record should no longer appear among the potential matches. In fact, if all the matchable fields were cleared, then there should be no potential matches

**Actual Result**
The list of potential matches is unaltered

**Comment by andreweskeclarke** [comment]
This is not a bug, discussed with Raymond and Tom.  We want to keep the history of all the matching enquiries, and believe it is not a common use case that Enquiries would change that much.
