### ISSUE TITLE
Display confirmed matches on mobile

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#202]
Once a field worker has confirmed a match from story #71 they should be able to view the confirmed matches on the mobile. When the field worker navigates to the list of matches to an enquiry, then will be able to view the confirmed and potential matches clearly distinguished/highlighted.

**Comment by baziwane** [comment]
GIVEN that I am a FIELD WORKER
WHEN I am viewing the list of matches to an enquiry using my mobile device
THEN I should be able to view a confirmed match (if any) at the top of the list
AND I should be able to view the remaining potential matches appearing below.

**Comment by tomclement** [comment]
Blocked due to https://github.com/rapidftr/tracker/issues/218

**Comment by tomclement** [comment]
Blockers resolved with https://github.com/rapidftr/RapidFTR-Android/pull/177

**Comment by tomclement** [comment]
Blocked due to https://github.com/rapidftr/tracker/issues/234

**Comment by tomclement** [comment]
https://github.com/rapidftr/tracker/issues/234 is now resolved with https://github.com/rapidftr/RapidFTR-Android/pull/186
