### ISSUE TITLE
Highlight as "Confirmed Match" on Child record and Enquiry

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#203]
When a child record is confirmed as a match to an enquiry in #71 there will be a highlighted text on both enquiry and child record that states that the record has been confirmed matching.

**Comment by baziwane** [comment]
GIVEN that I am a FIELD WORKER
WHEN I navigate to a child record that has been confirmed as match to an enquiry
THEN I should be able to view a text "Confirmed Matches: aabbccd" where aabbccd is the enquiry id shown as a link

GIVEN that I am a FIELD WORKER
WHEN I click on the enquiry by clicking on the enquiry id
THEN I should be able to view the details of the enquiry
AND I should view the text "Confirmed Matches: aabbccd" where aabbccd is the child id shown as a link

**Comment by tomclement** [comment]
Action Items:
- [x] Use a comma to separate the highlighted confirmed matches for a child record 
- [x] Use title field to display highlighted confirmed matches.

**Comment by tomclement** [comment]
[Card 221](https://github.com/rapidftr/tracker/issues/221) added to track the second action item - Use title field to display highlighted confirmed matches
