### ISSUE TITLE
Record a change log on mark/unmark as confirmed match

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#204]
GIVEN that I am a FIELD WORKER
WHEN I navigate to the change log for a child record that has been confirmed as a match to an enquiry
THEN I should be able to view a change entry with date and time of confirming as match, the name of the user who confirmed the match and the id of the enquiry to which it was matched

GIVEN that I am a FIELD WORKER
WHEN I navigate to the change log for enquiry that had been confirmed as matching a child record and then unconfirmed
THEN I should be able to view a change entry with date and time of unconfirming as match, the name of the user who unconfirmed the match and the id of the child record to which it was matched

**Comment by andreweskeclarke** [comment]
This card applies to any important status change for matches...  Any time a user changes a match to become Confirmed, Reunited, or Invalid, or changes a match out of those statuses, we should record a change log.
