### ISSUE TITLE
Add/display photos and audio for enquiries on mobile

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#212]
Forms
API

**Comment by tomclement** [comment]
Posting Acceptance Criteria from https://github.com/rapidftr/tracker/issues/174:

GIVEN that I am a FIELD WORKER
WHEN I am creating an enquiry using my mobile device
THEN I should be able to attach any photos and audio

GIVEN that I am a FIELD WORKER
WHEN I attach photos or audio to an enquiry and save using my mobile device
THEN I should be able to sync the record successfully
