### ISSUE TITLE
Highlighted field labels display as ‘null’ for unverified users

### ISSUE THREAD

**Issue by tomclement** [rapidftr/tracker#219]
**Steps to reproduce**
- Create an unverified user on the mobile
- Log in as that unverified user
- Create a new child or enquiry record
- Navigate to `View All` (for either child records or enquiry records)

**Expected Result**
The created record should be listed along with the highlighted fields and their corresponding labels

**Actual Result**
The highlighted field labels are displayed as ‘null’ (see screenshot below):

![null_values](https://cloud.githubusercontent.com/assets/5906754/4360387/6eac385e-427b-11e4-89a8-9135576d6132.png)

**Comment by ctumwebaze** [comment]
The reason this was failing is due to the fact that when unverified users signup on the mobile, they don't have a defined language. A method was added to the RapidFtrApplication class to return "en" as the default language for any current user whose language is not defined.

**Comment by tomclement** [comment]
Resolved with https://github.com/rapidftr/RapidFTR-Android/pull/188
