### ISSUE TITLE
Unable to mark child as duplicate

### ISSUE THREAD

**Issue by tomclement** [rapidftr/tracker#237]
Attempting to mark a child as duplicate results in the following error:

![mark_as_duplicate](https://cloud.githubusercontent.com/assets/5906754/4560732/422886ba-4ef7-11e4-91ea-d9a38e8ca80f.png)

**Comment by andreweskeclarke** [comment]
Some tests were commented out instead of fixed.  Fixed them up so that we won't miss this bug again.

**Comment by tomclement** [comment]
Resolved by https://github.com/andreweskeclarke/RapidFTR/commit/d80b23bfbbd7466dc0375e6c60cb785ca27f8429
