### ISSUE TITLE
Optimization: Internal pagination in mobile (list/search children) to support 5000 records

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#28]
- Move searching to a background thread with a progress dialog
- Use Pagination with a Producer/Consumer pattern. i.e.
  - Have a `Producer` that takes as input the `Cursor` (with records filtered using `LIKE`), and this should loop through the cursor and yield only the matching children
  - A Consumer should pick 10 records from the producer and display it on the screen. When the user scrolls to the end of the page, then it should fetch the next 10 records, and so on.
  - Have a look at [RxJava](https://github.com/Netflix/RxJava/wiki) for some examples.

**Comment by tomclement** [comment]
**[Update]** Results of testing behaviour of the mobile app with 5000 registered child records _(Note: The child records had neither photos nor histories):_
- There is delay of about 5 seconds in navigating to `View All`
- The performance of scrolling through the list of child records under `View All` depends on the phone used. On the Samsung Galaxy S4, apart from some subtle sluggishness on attempting to scroll through the entire list from top to bottom in one go, the behaviour was consistent with expectations. However attempting the same on a Samsung S Duos resulted in an error.
- There were no issues in navigating to `Search`
- The result of a search operation depends on the number of results. Testing was performed basing on search results of 1, 10, 100 and 1000 records. It was found that any search that returned up to about 100 records was manageable. However searches with 1000 results rendered the application unresponsive, as shown in the screenshot below:

![search_unresponsive](https://cloud.githubusercontent.com/assets/5906754/4421101/a757c0bc-4580-11e4-91f0-98007e67f572.png)
Generally, the operation of the application with 5000 records is currently very inefficient - as is depicted in how much of the phone's resources it uses in this state. See below:

![active_processes](https://cloud.githubusercontent.com/assets/5906754/4421137/f4c0620a-4580-11e4-8dc7-521b8e9e842a.jpg)
