### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#30]
The errors displayed when a user logs in or fails to sync aren't informative to enable a user decide the next course of action. This fix addresses the following list of errors displayed in the current version.
1. Failed to fetch form sections
2. Login unsuccessful
3. Sync failed, please try to login again
The following are possible scenarios to consider for sync and login failure
- server error
- permission denied
- session expired on mobile
- session expired on server
- offline login
- online login
- timeout of sync
- sync single record always says "Successful" even if failed

**Comment by rdsubhas** [comment]
Picked up by @ctumwebaze, @mwangiann and myself

**Comment by rdsubhas** [comment]
Error message references:
- [Login Page - Android](https://github.com/rapidftr/RapidFTR---Android/blob/master/RapidFTR-Android/res/values/strings.xml#L6)
- [Sync - Android](https://github.com/rapidftr/RapidFTR---Android/blob/master/RapidFTR-Android/res/values/strings.xml#L145)
- [Server Responses](https://github.com/rapidftr/RapidFTR/blob/master/config/locales/en.yml#L465)

**Comment by tomclement** [comment]
##### QA Remarks

---
- Toast is not shown on completion of synchronise all operation.
  - **Expectation** is that the toast messages should be shown at the end of any operation - whether successful or not
- When phone is offline, attempting to log in with the right credentials returns an error _Login failed. Incorrect username or password_.
  - **Expectation** is that error messages should be fine-grained enough to indicate that there is no active network connection
- It is currently not possible to log in offline (Always returns error messages that _Online login failed, will try to login offline_ and afterwards _Login failed. Incorrect username or password_.
  - **Expectation** is that this offline login with valid credentials should be possible after logging in with those credentials on that device at least once.
- It is currently not possible to log in as an unverified user. After signing up offline, restoring connectivity and then attempting to log in, error messages shown are _Invalid Credentials. Please try again!_ and then afterwards _Login failed. Incorrect username or password_.
  - **Expectation** is that it should be possible to log in as a signed-up unverified user, provided the correct set of credentials are used

**Comment by tomclement** [comment]
The first time a user attempts to log in, if they are offline, the login obviously fails because there are no cached credentials. However the error message they see is _Login Failed, Incorrect username or password_. This needs to be changed to something more meaningful to the user so that the user is prompted to check their network connection

**Comment by baziwane** [comment]
Here's the scenarios to consider to resolve this issue:

GIVEN that I am a FIRST TIME USER,
AND I am attempting to login into RapidFTR in offline mode using my mobile device,
WHEN I provide a username and password AND click on the login icon,
THEN I should be able to see an error message "Login failed, first time users please login online to enable your account for offline mode"

GIVEN that I am ANY USER,
AND I have previously accessed RapidFTR online using my mobile device,
AND I am attempting my login in offline mode on the same device,
WHEN I provide an invalid username or password,
THEN I should see an error message "Login failed, incorrect username or password"

**Comment by tomclement** [comment]
Now resolved with [Pull 137](https://github.com/rapidftr/RapidFTR---Android/pull/137)
