### ISSUE TITLE
Failed to switch between instances on same device

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#32]
When a user provides a different URL on their mobile device, they're logged into the instance that was provided during initial set up/. This fix will ensure that a user can login to different instances using the same device.

**Comment by rdsubhas** [comment]
We need to add documentation on how Multiple servers/users works in Android. Since this is deployment/administration information, add this to the Guides instead of the Wiki. Basically, if someone is working across multiple servers, and doesn't want the data to get mixed - please use different usernames.

Changing the estimate to "Tiny" because its just documentation.

**Comment by baziwane** [comment]
Test that field worker doesn't sync data across instances especially if using same username for both instances.

**Comment by tomclement** [comment]
In the current implementation, it is possible to switch between instances by specifying a different URL. This works even when the different instances share a username.

For example, given the following instances:

| Instance Name | Existing Users |
| --- | --- |
| https://instance1.rapidftr.com | user1, field_worker |
| https://instance2.rapidftr.com | user2, field_worker |

**Online operation**
- If user1 or field_worker logs into the mobile and specifies the instance1 url, they are able to log in and see (and manipulate data for only instance 1)
- Similarly, If user2 or field_worker logs into the mobile and specifies the instance2 url, they are able to log in and see (and manipulate data for only instance 2)
- If user1 attempts to log in with the instance2 url, or user2 attempts to log in with the instance1 url, they are presented with the error message `Invalid Credentials`

**Offline operation**
- For the distinct users (user1 and user2), offline login will always present the user with the data from their instance
- For the user _field_worker_ that shares a username across instances, the operation is such that logging in offline with this username will present the user with the data from the last logged-into instance

**Syncing**
- A peculiarity is that selecting `Synchronise All` always attempts to perform the sync against the last logged-into instance. This means that if _instance1_ was the last logged-into instance, and for some reason user2 is able to log in offline, then when user2 logs in they will be presented with the data from instance2. When user2 selects `Synchronise All` the mobile will attempt to perform the sync against instance1. Fortunately, from testing, this results in a _session expired_ error, requiring user2 to first log in online (at which point they will have to specify the correct instance).
