### ISSUE TITLE
Move to GitHub Issues

### ISSUE THREAD

**Issue by rdsubhas** [rapidftr/tracker#34]
Move to GitHub issues for issue tracking, and Waffle for the board.

Open Issues:
- Documentation on new procedure of picking up and contributing stories
- Story pipeline/flow
- Milestones/Label structure
- Announce in Google group

**Comment by rdsubhas** [comment]
@zkhan I saw [your comment](https://github.com/rapidftr/RapidFTR/issues/632#issuecomment-45589927), but unfortunately it seems that page is no longer accessible, and I can see only the snippet O_o Can you pls repost it here?

**Comment by duelinmarkers** [comment]
I tried following the links to @zkhan's comments too. I guess github allows
replies by email to issues on projects where issues have since been
disabled. Kind of annoying.

**Comment by zkhan** [comment]
Sorry guys, let me try here. I thought I was responding to the google group
not the repo!

In response to your request for comment on using Elastic search, I just
thought:

Hi Subhas,

It's great to be able to see how much work you're putting in though the new
tracker repo. I saw this post and had a question. I think we chose Solr,
and non cloud backed tech in general, to ensure a ad-hoc set up could be
created without any wider internet access. We did that with no direction,
and you're really fortunate to have great knowledge and feedback from
actual deploys! So do you know that's not a problem / have a different use
case for the elastic search stuff, perhaps a better architecture than one
app does all?

**Comment by rdsubhas** [comment]
Hi @zkhan thanks for the feedback! ElasticSearch is also similar to Solr and works offline too, so we won't be needing internet/cloud access for it :)
