### ISSUE TITLE
Use Gradle instead of Maven, Ensure gradle android unit tests

### ISSUE THREAD

**Issue by rdsubhas** [rapidftr/tracker#39]
The project has now been simplified to a single-module (single pom.xml) project. Previously it was one parent with two child projects which caused a lot of IDE issues.

This makes it easier to move from Maven to Gradle. We already spiked on Gradle and here are the observations:
- Gradle works very well. Doesn't download the internet, downloads very small amount of dependencies
- The Android plugin works very well. APK builds are much faster
- **Major Bottleneck:** Ability to run Android unit tests. The Gradle android plugin has no clear way to run the Unit tests alone, and it always runs unit tests as part of the integration tests (and consequently tries to look for emulator and stuff). This is a known issue with Gradle Android plugin, and many (hackish) projects have come up to provide Unit testing support. Most of those don't work well with the IDE. Some don't work well with Robolectric. So if those issues can be made easy, we welcome the switch to Gradle.

**Comment by AbrahamKiggundu** [comment]
Totally agree with the spike results from my past experience with Gradle and Maven. Will start taking a look at this especially in light of the recent switch to calabash for the integration tests.

**Comment by AbrahamKiggundu** [comment]
This has been done and a pull request submitted
Points to note:
- The maven build has not been disabled and should still work fine pending on QA of the Gradle build and update of Travis and Snap
- Though calabash gradle plugin has been added its integration needs to be properly tested and polished so recommend we continue using external `calabash-android run <apk>` at the command line.
- Some minor compatibility issues with Hamcrest matchers demanded minor code changes to the tests that should be review
- Documentation has not been updated pending on review/acceptance of the pull request changes

**Comment by AbrahamKiggundu** [comment]
Some of the calabash test failed on integration of the request even though the request includes no code changes. Hopefully this is not a sign of emerging instability of the acceptance tests.

Won't be able to look into this much further for now so please feel free to pick this up by commenting below.
If it hasn't been picked up when I next get time to look at it i'll add a comment to let everyone know.

**Comment by tomclement** [comment]
Hey @AbrahamKiggundu, I suspect the failing integration tests are related to parallel builds. See [here](https://github.com/rapidftr/tracker/issues/107). If that's the case, then this issue should be resolved shortly, since I'm in the process of adding Mimic.

**Comment by AbrahamKiggundu** [comment]
cool
thx @tomclement

**Comment by rdsubhas** [comment]
Update: Gradle doesn't yet support proper IDE integration, so running individual tests (or group of tests) directly from the IDE is not yet possible, and that would hamper development. So closing this until Gradle adds proper unit testing support.
