### ISSUE TITLE
 Introduce Code Quality metrics as a rake task

### ISSUE THREAD

**Issue by rdsubhas** [rapidftr/tracker#4]
Currently we're not tracking Code Quality metrics in any stage. We need to add that as a rake task so that we can fail the build whenever code quality goes down.

[CodeClimate](//codeclimate.org) does an excellent job, and that's where we'd like to be. But unfortunately it can't be integrated into the rake tasks - it simply runs after merging, which makes it an afterthought.

We need some tool that can directly run as a rake task, raise an error and fail the build if metrics are going down. [ruby-toolbox](https://www.ruby-toolbox.com/categories/code_metrics) has a good selection of gems for this purpose.

**Comment by rdsubhas** [comment]
[Cane](https://github.com/square/cane) looks very interesting and lightweight...

**Comment by AbrahamKiggundu** [comment]
I'm currently looking into this

**Comment by AbrahamKiggundu** [comment]
Done.
See relevant [pull request](https://github.com/rapidftr/RapidFTR/pull/647) for details
