### ISSUE TITLE
Remove hard coded values in web forms

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#40]
Some Default Fields are hard coded in code (e.g. Name, Protection Status, FTR Status, etc). We need to remove these hard coded values to make the Form Builder as customizable as we want it to be.

**Comment by rdsubhas** [comment]
##### Areas to cover:
- [x] Rails Views
- [x] Rails Models
- [x] CouchREST Views
- [x] Solr
- [ ] Migrations
- [ ] Make sure to remove all perm_enabled and perm_visible FormSection/Field

##### List of Identified fields:

Essential for core operation (Mark as Reunited, Enquiries, Search, etc):
    Protection Status
    FTR Status
    Name 

Name: 
    Used in many places (text_to_identify_child)
    wherever child name is shown, its shown as <NAME> (ID) e.g. Test (abcdefgh)
    List
    Search
    Profile (title)

Weekly Report:
    gender, protection_status, ftr_status

CPIMS:
    most fields in basic identity, caregiver info, family info

Mobile:
    Name (hardcoded in database as well)

Other:
    Photo
    Audio

##### More tasks:

Hide Field - Why is it used?
~~Two specs taking 45 seconds (out of 2 mins)~~
Use TimeCop
Child.schedule needs to be called
Change all migrations to use Child.all.rows.each do .... (CouchREST built in lazy load syntax)

**Comment by rdsubhas** [comment]
**Questions for Stuart:**
- Reporting feature depends on Protection Status, FTR Status and Gender fields. If these fields are changed, Reporting breaks. One option is to use the Advanced Search until we have the Dynamic reports as envisioned.

**Comment by scampo** [comment]
Ideally, we would be able to mark fields that you can generate reports with, just as we will be able to mark fields as filterable, sortable, searchable.

Having never seen a report in RapidFTR, I don't know how it was originally envisioned. Would it be possible to have a 'generate report' option from any advanced search? Maybe that would make more sense than specifying what fields can generate reports? Then the report output would specify all of the variables defined in the search and provide aggregates of the values for each field. Does that make sense?

**Comment by rdsubhas** [comment]
@scampo We'll have a huddle on this to, but having a dynamic report seems to be more flexible than marking fields as reportable (because marking as reportable would enable only one type of report, whereas doing an advanced search will allow to generate a lot of different reports). What we're also looking at is, do we need to export it as a file or render it as a table in the page itself, and whether are there any out-of-the-box solutions that can pivot the data...

**Comment by scampo** [comment]
@rdsubhas  -- great, got it. We would want to be able to export the file, not just render it in the page, so please keep that in mind!

**Comment by andreweskeclarke** [comment]
Reports, which are inherently hard coded, will be addressed in a separate story.  To dynamically generate reports will take a story, which is not fully fleshed out.

**Comment by andreweskeclarke** [comment]
When creating new migratons, developers must reindex the Solr indexes if they are changing data that would affect searching, filtering, ordering, or sorting.

**Comment by tomclement** [comment]
Should be good to go, except for issues https://github.com/rapidftr/tracker/issues/138 and https://github.com/rapidftr/tracker/issues/137 - Maybe we should track these separately?

**Comment by baziwane** [comment]
Yes, we'll track separately from this story.

Thx

On Mon, Jul 21, 2014 at 4:27 PM, Tom Clement Oketch <
notifications@github.com> wrote:

> Should be good to go, except for issues #138
> https://github.com/rapidftr/tracker/issues/138 and #137
> https://github.com/rapidftr/tracker/issues/137 - Maybe we should track
> these separately?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rapidftr/tracker/issues/40#issuecomment-49604703.

## 

_Raymond B. Matovu__Business Analyst | ThoughtWorks Uganda__# 23 Soliz
House | Lumumba Avenue | Nakasero__email. rmatovu@thoughtworks.com
rmatovu@thoughtworks.com *_o. +256 204 007 000 | m. +256 778 686 569|
skype. baziwane rmatovu@thoughtworks.com*
[image: ThoughtWorks] http://www.thoughtworks.com/
