### ISSUE TITLE
Enable sorting by any field

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#41]
![screen shot 2014-07-17 at 9 34 01 am](https://cloud.githubusercontent.com/assets/4676831/3609536/61f1e1e2-0d7c-11e4-9bd8-6429c117c4d8.png)
 When viewing child records on the web, a field worker should be able to sort the records based on the field specified.

**Comment by baziwane** [comment]
GIVEN that I am an ADMIN
WHEN I am defining a form using form builder
THEN I should have the option to mark a field as sortable

GIVEN that I am a FIELD WORKER
WHEN I am viewing child records on my netbook
THEN I should be able to sort the records by the marked fields.

GIVEN that I am a FIELD WORKER
WHEN I am viewing child records on my netbook
AND the ADMIN has unmarked any of the fields as not being sortable
THEN I should not be able to sort the records by the unmarked fields.

**Comment by andreweskeclarke** [comment]
Additionally, we removed the sorting cucumber tests around sorting by name on the Child index page.  Make sure to cover the new sorting results with functional tests.

**Comment by baziwane** [comment]
We're changing the order by records to contain all fields from which the user can sort by. The following image is a sample of the kind of drop down menu we'll be using. It will enable the user to search for a specific field they'd like to order records by.
![screen shot 2014-07-17 at 1 14 10 pm](https://cloud.githubusercontent.com/assets/4676831/3611464/2aa06276-0d9b-11e4-9fe3-69a612a7b08b.png)

**Comment by andreweskeclarke** [comment]
New acceptance criteria:

GIVEN that I am a FIELD WORKER
WHEN I am viewing child records on my netbook
THEN I should be able to sort the records by any field.

**Comment by andreweskeclarke** [comment]
Also, users should be able to switch between sorting in ascending and descending order for each field.  A toggle-able pair of up/down arrows is the preferred UI technique.
