### ISSUE TITLE
Enter and search multi-lingual data

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#47]
This feature shall enable support for multi lingual deployments of RapidFTR. A user should be able to search for data in a preconfigured language using their device. At the moment, any text with accented characters isn't well displayed on the screen and searches using these characters do not return any results.

**Comment by baziwane** [comment]
GIVEN that I am a FIELD WORKER
AND I am registering a separated/unaccompanied child using my mobile device
WHEN I enter an accented character in the name of the child e.g. Amôur
THEN the child's name should be saved in the same format that I entered.

GIVEN that I am a FIELD WORKER
WHEN I am searching for a child record with an accented character e.g. Amôur using my mobile device
THEN I should be able to view all results that match the criteria I am searching.

**Comment by tomclement** [comment]
Feature added with https://github.com/rapidftr/RapidFTR---Android/pull/147 - Pending integration tests

**Comment by tomclement** [comment]
Integration tests added with https://github.com/rapidftr/RapidFTR---Android/pull/151
