### ISSUE TITLE
One Click Install (Windows/Netbook)

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#49]

**Comment by baziwane** [comment]
GIVEN that I AM a  SYSTEM ADMINISTRATOR
WHEN I am reading RapidFTR documentation
THEN I want to be able to find instructions on how to set up windows netbooks

**Comment by tomclement** [comment]
RapidFTR 2.0.0 installer for Windows is now available at http://bit.ly/rapidftr under the **server** directory
