### ISSUE TITLE
Download form sections and fields for enquiries to mobile (API)

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#53]

**Comment by baziwane** [comment]
Ensure backwards compatibility with v1.2

**Comment by tomclement** [comment]
This is supposed to ensure that the form sections and fields for enquiries (created using the form builder) can be downloaded to the mobile on the 2.0 APK. At the same time, the 1.2.1 APK should still be able to work with the new RapidFTR server given these changes. Presently backwards compatibility is broken (see #155)

**Comment by tomclement** [comment]
Backwards compatibility resolved with rapidftr/RapidFTR---Android/pull/154
