### ISSUE TITLE
View form sections and fields for enquiries on mobile

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#54]
This feature simply tracks the ability for a field worker to view latest form sections and fields on their mobile. Any changes to form sections and fields should cascade to device upon syncing form sections. In addition, they should be able to save an enquiry on their device.

**Comment by ctumwebaze** [comment]
things to look into.
~~1. Synchronization~~
2. Saving of Enquiries
3. This may change the way the enquiries on the server end is handled.

**Comment by baziwane** [comment]
Tracking sync in #152

**Comment by tomclement** [comment]
This story is currently defective. See #156

**Comment by tomclement** [comment]
Related defect https://github.com/rapidftr/tracker/issues/156 closed with rapidftr/RapidFTR---Android/pull/155. All else looks good.
