### ISSUE TITLE
Edit an Enquiry

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#56]
The ability to edit a saved/submitted enquiry is a useful feature to have for any data driven application. This feature will ensure that users with correct permissions are able to edit/update a saved enquiry. While viewing an enquiry, the user shall navigate to the edit page by clicking on the edit icon. The edit page will display the enquiry form with all completed fields in editable format. The user will then update the fields and click on a save icon.

**Comment by baziwane** [comment]
There will be a number of checks to consider during editing but these will be tracked in separate stories e.g. recording a change log, triggering a match/smart search, etc.

**Comment by baziwane** [comment]
GIVEN that I am a USER
AND I have the correct permissions to edit an enquiry
WHEN I am viewing an enquiry 
THEN I should be able to view an edit icon

GIVEN that I am a USER
AND I have the correct permissions to edit an enquiry
WHEN I click on the edit icon and navigate to the edit enquiry page
THEN I should be able to view the list of enquiries form sections and fields pre-filled with the data

GIVEN that I am a USER
AND I have correct permissions to edit an enquiry
WHEN I update any of the fields in the form and click on save icon
THEN I should be able to see a success message indicating that the record was successfully saved.
AND I should be able to view the form in readonly format with fields I just updated/completed.

Rules
-[ ] Cancel icon to abort edit
-[ ] Save without editing any of the form fields (to be confirmed)
-[ ] Edit link should display on each enquiry in the listing page

**Comment by tomclement** [comment]
Feature added with rapidftr/RapidFTR/pull/716

**Comment by tomclement** [comment]
Pending fix for rapidftr/tracker/issues/180

**Comment by tomclement** [comment]
#180 fixed with https://github.com/rapidftr/RapidFTR-Android/pull/169
