### ISSUE TITLE
View all enquiries

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#57]
Many times field workers and admins need to view a list of enquiries recorded in an emergency. The purpose of this feature is to create a list page for enquiries on the web. Attached is a mockup of this feature.
![enquiries](https://cloud.githubusercontent.com/assets/4676831/3811006/03fcff46-1c99-11e4-88ca-9bbf713f3468.png)

**Comment by baziwane** [comment]
GIVEN that I am a USER
AND I have correct permissions to view enquiries
WHEN I log into RapidFTR using my netbook
THEN I should be able to view a tab "Enquiries" in the top menu

GIVEN that I am a FIELD ADMIN
AND I have correct permissions to view enquiries
WHEN I click on the Enquiries tab in the top menu
THEN I should be able to view a list of all enquiries

GIVEN that I am a FIELD WORKER
WHEN I navigate to the view enquiries page
THEN I should be able to view only enquiries

Rule
[ ]- pagination at the bottom of the list page
[ ]- use highlighted fields for enquiry as displayed fields
[ ]- show register new enquiry button at the top of the list
[ ]- display enquirer's photo

**Comment by baziwane** [comment]
@scampo please confirm:
a) a field admin viewing the list of enquiries on the web can view all enquiries in the system
b) a field worker viewing list of enquiries on the web can only view own (created by self) enquiries

**Comment by scampo** [comment]
This is correct, Raymond.

_____________________
Stuart Campo
Innovation Unit, UNICEF
scampo@unicef.org

+254.718.764526 (Kenya)*
+211.921.379121 (South Sudan)
+256.779.234347 (Uganda)
+1.802.249.8233 (U.S.)
 Skype: stuart.campo

*_currently in Kenya_

www.unicefstories.org

**Comment by baziwane** [comment]
@scampo as agreed there is no need to silo information on the web therefore a field worker will be able to view and search all enquiries on the web if correct permissions assigned, thus ignore my previous comment.

GIVEN that I am a FIELD WORKER
WHEN I navigate to the list enquiries page
THEN I should both enquiries I created and enquiries created by other field workers in my location/instance.

**Comment by tomclement** [comment]
Moving this to [QA Blocked](https://github.com/rapidftr/tracker/labels/Status:%206.%20QA%20Blocked) because of rapidftr/tracker/issues/176

**Comment by tomclement** [comment]
Identified defects (rapidftr/tracker#176) resolved with rapidftr/RapidFTR#717
