### ISSUE TITLE
Mark a child record as "Not Matching" an enquiry

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#59]
The process of matching enquiries to child records involves building a criteria based on all fields in an enquiry. In most cases, the system shall return records that have matched certain aspects of enquiry to child record but not an exact match. In this case, the case worker has to manually mark the child record as not matching so that it's not returned in subsequent viewing of potential matches. 
When the field worker is viewing an enquiry and list of potential matching child records, they'll have the ability to click on an icon to remove the child record from list of potential matches for this enquiry.

**Comment by baziwane** [comment]
GIVEN that I am a FIELD WORKER
WHEN I am viewing the list of potential child matches to an enquiry
THEN I should be able to see a remove icon next to a child record

GIVEN that I am a FIELD WORKER
WHEN I click on the remove icon next to a child record in the list
THEN the child record should be removed from list of potential matches of this enquiry

GIVEN that I AM A FIELD WORKER
WHEN I mark a record as not matching
THEN I should see a success message on my screen

**Comment by baziwane** [comment]
@scampo, when a child record is marked as "not matching" should we track this event in the change log for the child record or change log for the enquiry or both?

**Comment by scampo** [comment]
This should be tracked in the change logs of both records.

_____________________
Stuart Campo
Innovation Unit, UNICEF
scampo@unicef.org

+254.718.764526 (Kenya)
+211.921.379121 (South Sudan)
+256.779.234347 (Uganda)
+1.802.249.8233 (U.S.)
 Skype: stuart.campo

**currently on mission in Mali, available on U.S. number *

www.unicefstories.org
