### ISSUE TITLE
Show list of matching enquiries when viewing a child record

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#60]
When viewing a child record on a mobile device, a field worker should view the list of matching enquiries for the record.  RapidFTR supports viewing  details of a child record created by a field worker, and upon search details of records created by other case workers. When viewing these details, the ability to view the matching enquiries should be available.

**Comment by tomclement** [comment]
Blocked due to https://github.com/rapidftr/tracker/issues/201

**Comment by tomclement** [comment]
Unblocking this as #201 is now resolved with https://github.com/rapidftr/RapidFTR-Android/pull/175
