### ISSUE TITLE
Assign permissions for creating, editing and viewing enquiries

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#62]
System administrators should have ability to determine which user roles have access to the enquiries features. Using the web interface the admin will assign permissions for creating, updating and viewing enquiries. Once a given user role is assigned the permissions, upon logging in on the mobile device or web browser, they will be able to view the enquiries feature. Upon deassigning, they will no longer have access.

**Comment by baziwane** [comment]
GIVEN that I am a SYSTEM ADMIN
WHEN I log into RapidFTR
THEN I should have options to assign permissions to create & edit enquiries to a role

GIVEN that I am a SYSTEM ADMIN
WHEN I log into RapidFTR
THEN I should have options to assign permissions to view all & search enquiries to a role

GIVEN that I am a REGISTRATION WORKER
AND I have been assigned permissions to create and edit enquiries
WHEN I log into my mobile device
THEN I should be able to register new enquiries and edit existing ones
AND I should be able to sync my records successfully.

GIVEN that I am a REGISTRATION WORKER
AND I have been assigned permissions to create and edit enquiries
WHEN I log into my web browser
THEN I should be able to register new enquiries and edit existing ones.

GIVEN that I am a REGISTRATION WORKER
AND I have been de-assigned permissions to create and edit enquiries
WHEN I log into my web browser
THEN I should NOT be able to register new enquiries and edit existing ones
AND I shouldn't be able to view the Enquiries tab

GIVEN that I am a REGISTRATION WORKER
AND I have been de-assigned permissions to create and edit enquiries
WHEN I log into my mobile device
THEN I should NOT be able sync enquiries with the server

GIVEN that I am a REGISTRATION WORKER
AND I have been assigned permissions to view all and search enquiries
WHEN I log into my mobile device
THEN I should be able to search for enquiries and view all my enquiries

GIVEN that I am a REGISTRATION WORKER
AND I have been assigned permissions to view all and search enquiries
WHEN I log into my web browser
THEN I should be able to search for enquiries and view all my enquiries

GIVEN that I am a REGISTRATION WORKER
AND I have been de-assigned permissions to view all and search enquiries
WHEN I log into my mobile device
THEN I should NOT be able to search for enquiries and view all my enquiries on my device

GIVEN that I am a REGISTRATION WORKER
AND I have been de-assigned permissions to view all and search enquiries
WHEN I log into my web browser
THEN I should NOT be able to search for enquiries and view all my enquiries

**Comment by tomclement** [comment]
**Notes**
Presently, if a user has the _'Create Enquiry'_ Permission and not the _'View Enquiries'_ permission, when that user creates a new enquiry record on the mobile and performs a sync, they encounter the error message `Error in syncing. Try again later`. What actually happens is that the new record is created on the server but because the user has no _'View Enquiries'_ permission, they are unable to retrieve records from the server - hence the error.

~~To avoid such an error, administrators have to be advised to grant any role that has a _'Create Enquiry'_ permission the _'View Enquiries'_ permission as well.~~

**[Update]** The _'Create Enquiry'_ permission should inherently include a _'View Enquiries'_ permission as well

**Comment by mwangiann** [comment]
A user with create permissions will also have view permissions.  The notification message on mobile in case the sync failure is due to authorisation has been changed to correctly state that.
