### ISSUE TITLE
Trigger check for matches after creating or editing a child record

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#63]
When a child record is created or edited by a field worker and saved, the smart search feature will be triggered to find potentially matching enquiries.  A field worker viewing the child record on the web and mobile device will be able to view the potential matching enquiries to the child record immediately.

**Comment by baziwane** [comment]
GIVEN that I AM a FIELD WORKER
WHEN I create or edit a child record and hit save button in my browser
THEN I should be able to view potentially matching enquiries to this record

GIVEN that I AM a FIELD WORKER
WHEN I am viewing the child record on my mobile device
THEN I should be able to view the matching enquiries

**Comment by tomclement** [comment]
Feature added with https://github.com/rapidftr/RapidFTR/pull/737
