### ISSUE TITLE
Record and view change log for enquiries on web

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#68]
Change logs enumerate the change activity that occurs against a record over time. Enquiries being standard documents in the child protection space require tracking any changes that are made against the details. Each time a user updates an enquiry we'll track the user's id, date & time change occurred, photo changes, on failed matching by a case worker, etc

**Comment by baziwane** [comment]
GIVEN that I am any USER
AND I have access to viewing an enquiry change log
WHEN any of the following changes are made against an enquiry:
- On create
- On update
- ~~On matching an enquiry~~
- ~~On "Not matched" with a child record~~

THEN a change log should be recorded.

GIVEN that I AM an ADMIN
WHEN I navigate to an enquiry
THEN I should be able to view all change logs recorded against it.

GIVEN that I am an ADMIN
WHEN I am viewing details of a change log on an enquiry
THEN I should be able to view the name of the user who initiated the update, the date and time the update was done and a brief description of the nature of the update.

**[Update]** Change log entries as a consequence of confirming (or un-confirming) enquiry matches are being tracked in https://github.com/rapidftr/tracker/issues/204

**Comment by tomclement** [comment]
Feature added with https://github.com/rapidftr/RapidFTR/pull/733
