### ISSUE TITLE
Filter Enquiries

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#73]

**Comment by tomclement** [comment]
Rather than specifying filterable fields and using them to filter, filtering enquiries is to be performed by the following pre-defined fields:
- Reunited
- Has matches
- Has Confirmed Match

**Comment by andreweskeclarke** [comment]
This story does not include ordering

**Comment by tomclement** [comment]
Feature added with https://github.com/rapidftr/RapidFTR/pull/768
