### ISSUE TITLE
Setup Release Artifacts Repository

### ISSUE THREAD

**Issue by rdsubhas** [rapidftr/tracker#84]
We need to setup an artifactory for hosting the releases (installers, apk, etc). This can be anything, ranging from GitHub Releases, DropBox, Google Drive, to the RapidFTR website. Need to figure out the right place to host.

The only caveat being, generated installers are around 450 MB in size. So GitHub issues or other lightweight solutions may not be appropriate.

**Comment by rdsubhas** [comment]
Spiked on the following:
- [DropBox Folder](http://bit.ly/rapidftr)
  - Used [Dropbox Uploader](https://github.com/andreafabrizi/Dropbox-Uploader)
  - Integrated [Snap CI](https://snap-ci.com/rapidftr/RapidFTR---Android/) to automatically upload the APK
  - Good: Works well, Bad: 2 GB limit
- [Google Drive Folder](https://drive.google.com/folderview?id=0BwGvt_EicHVvaE43RkozaERPOGc&usp=sharing#list)
  - Used [GDrive](https://github.com/prasmussen/gdrive) to upload
  - Good: 15 GB limit, Bad: UI shows unnecessary preview window :(

Both can be easily integrated. Using DropBox for now for the simpler UI.

So, Releases page http://bit.ly/rapidftr has been updated in the README and Wiki. Actually this Releases page can remain the same, even if later we switch to Google Drive or something, we can still point bit.ly/rapidftr to the new folder.

**Comment by rdsubhas** [comment]
Need to make the Unstable (development) APK have a completely different name and package from the main production APK, so that people can have both running side by side. This is tracked as a separate effort, since some internal shared folders also have to be changed.

**Comment by tomclement** [comment]
@rdsubhas @ctumwebaze @austiine04 @mwangiann Refer to preceding comment >> where is this being tracked? (Differentiating the development APK from the production APK)

**Comment by tomclement** [comment]
Closing this, as differentiating between development and production APK is being tracked in https://github.com/rapidftr/tracker/issues/92
