### ISSUE TITLE
Set up staging environment

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#87]
Setup `uat.rapidftr.com`, and a one-click deployment in the CI to this same.

**Comment by ctumwebaze** [comment]
I will be taking this one with @mwangiann

**Comment by ctumwebaze** [comment]
The server is up and running at http://uat.rapidftr.com

**Comment by baziwane** [comment]
Great job!
Thx

On Fri, Jun 20, 2014 at 10:47 AM, ctumwebaze notifications@github.com
wrote:

> The server is up and running at http://uat.rapidftr.com
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rapidftr/tracker/issues/87#issuecomment-46653037.

## 

_Raymond B. Matovu__Senior Consultant_
Emailrmatovu@thoughtworks.com
Telephone+256 778 686 569
[image: ThoughtWorks] http://www.thoughtworks.com/

**Comment by rdsubhas** [comment]
NOTE: `demo` and `uat` are running in the same machine.
We have backed up the data in `demo.rapidftr.com` since we had to format the machine. Will bring up demo with all the old data subsequently.
