### ISSUE TITLE
Fix Encryption in Android 4.2 devices

### ISSUE THREAD

**Issue by rdsubhas** [rapidftr/tracker#96]
Android 4.2 has changed SecureRandom implementation. This has caused AES encryption to break in [many applications](https://www.google.com/search?q=stackoverflow+android+4.2+aes). Right now, we have made some fixes purely for backwards compatibility. But we need to change the Encryption mechanism to reflect the changes in principle.

This would most likely be a non-backwards-compatible upgrade, and has to be paired with #27

**Comment by baziwane** [comment]
We're triaging this story instead of #33
